<a href="https://colab.research.google.com/github/RaghavendraTevari/Bank_Analytics/blob/main/Real%20Estate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape


(3,)

In [ ]:
arr = np.array([[[[]]]])

In [ ]:
arr.shape

(1, 1, 1, 0)

In [ ]:
range = np.arange(1,10)

In [ ]:
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1,10,2)

In [ ]:
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1,5)

In [ ]:
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.logspace(1,3,3)

In [ ]:
arr

array([  10.,  100., 1000.])

In [ ]:
arr = np.zeros(5)

In [ ]:
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3])

In [ ]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([4,2])

In [ ]:
arr = np.full(10,2)

In [ ]:
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4],7.1)

In [ ]:
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [ ]:
e = np.empty([2,3])

In [ ]:
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.random.rand(10)

In [ ]:
arr

array([0.92870603, 0.21776127, 0.38975481, 0.70934603, 0.17408547,
       0.52441416, 0.67398818, 0.67971192, 0.734882  , 0.91734653])

In [ ]:
arr = np.random.rand(2,3)

In [ ]:
arr

array([[0.71452765, 0.70037923, 0.71256681],
       [0.80316642, 0.92324481, 0.92922592]])

In [ ]:
arr = np.random.randn(2,3)
arr

array([[-0.21487971, -0.57385639,  0.43702288],
       [ 0.47777814,  0.85872389,  1.68518745]])

In [ ]:
a = np.random.randint(10,100,) -> #start,stop,interval
a

39

In [ ]:
a = np.random.randint(10, 100, size = (2,3))
a

array([[83, 47, 97],
       [46, 64, 67]])

Numpy Datatypes and Typecasting

In [ ]:
a= np.array([1,2.1,3])
a

array([1. , 2.1, 3. ])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a= np.array([1,2,3,4], dtype=np.float64)
a


array([1., 2., 3., 4.])

In [ ]:
type(a)

numpy.ndarray

Type casting As astype

In [ ]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
new_arr= a.astype(np.float64)

In [ ]:
new_arr.dtype

dtype('float64')

In [ ]:
a= np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a.itemsize

8

Array Reshaping-> Reshape,Ravel,Flatten

In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

Revel-> Convert 1D array

In [ ]:
ravel = reshaped.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.zeros(2)
a

array([0., 0.])

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
np.sqrt(arr)

array([1., 2., 3., 4.])

Exponential

In [ ]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


Sine

In [6]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [7]:
np.cos(angles)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

Indexing and Slicing

In [ ]:
a=([1,2,3,4,5])

In [ ]:
a[::-1]

[5, 4, 3, 2, 1]

In [ ]:
a[::2]

[1, 3, 5]

In [9]:
a= np.array([1,2,3,4])
b= np.array([7,8,9,10])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
b


array([ 7,  8,  9, 10])

In [12]:
a+b

array([ 8, 10, 12, 14])

In [14]:
a[1::2]

array([2, 4])

In [22]:
b[::-1]

array([10,  9,  8,  7])

Matrix

In [23]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                   [7,8,9]])

In [44]:
print(matrix[0:3,1:2])

[[2]
 [5]
 [8]]


Index Arrays

In [46]:
arr = np.array([10,20,30,40,50])
ind= [0, 2]
print(np.take(arr, ind))


[10 30]


Iterating

In [48]:
arr = np.array([[1,2],[3,4]])

In [49]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

Views and Copies

In [56]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [57]:
view[0] = 200

In [58]:
view

array([200,   3])

In [59]:
arr

array([  1, 200,   3,   4,   5])

In [60]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [61]:
copy[0] = 2

In [63]:
copy

array([2, 3])

In [64]:
arr

array([  1, 200,   3,   4,   5])